"""
GreenSynth Analytics — Phase 21 Scientific PDF Report DTO Schemas

Structured Data Transfer Objects decoupling database ORM entities from
ReportLab PDF rendering logic.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class ProvenanceItemSchema(BaseModel):
    sample_code: str
    technique: str
    raw_filename: str
    raw_file_id: str
    sha256_checksum: str
    analysis_run_id: str | None = None
    analysis_method: str | None = None
    software_version: str = "1.0.0-research"
    processing_parameters: dict[str, Any] = Field(default_factory=dict)
    calculated_properties: list[dict[str, Any]] = Field(default_factory=list)


class XRDReportSectionSchema(BaseModel):
    available: bool = False
    raw_filename: str | None = None
    analysis_version: str | None = None
    processing_parameters: dict[str, Any] = Field(default_factory=dict)
    peaks: list[dict[str, Any]] = Field(default_factory=list)
    crystallite_size_nm: float | None = None
    formula_used: str = "Scherrer Equation: D = (K * λ) / (β * cos θ)"
    disclaimer: str = "Peak positions and FWHM reported from software analysis. Phase identification requires reference comparison."
    plot_bytes: bytes | None = None


class UVVisReportSectionSchema(BaseModel):
    available: bool = False
    raw_filename: str | None = None
    analysis_version: str | None = None
    transition_type: str = "Direct Allowed (γ = 0.5)"
    optical_band_gap_ev: float | None = None
    tauc_equation: str = "(α * hν)^(1/γ) vs hν"
    plot_bytes: bytes | None = None


class ElectricalReportSectionSchema(BaseModel):
    available: bool = False
    raw_filename: str | None = None
    measurement_type: str = "Two-Point Probe I-V Fitting"
    thickness_nm: float | None = None
    width_mm: float | None = None
    length_mm: float | None = None
    resistance_ohms: float | None = None
    resistivity_ohm_cm: float | None = None
    conductivity_s_cm: float | None = None
    r2_score: float | None = None
    plot_bytes: bytes | None = None


class StatisticalReportSectionSchema(BaseModel):
    available: bool = False
    analysis_type: str | None = None
    sample_size_n: int = 0
    metrics: dict[str, Any] = Field(default_factory=dict)
    disclaimer: str = "Statistical findings report observed associations in the available dataset. Causality requires scientific verification."


class MLPredictionReportSectionSchema(BaseModel):
    available: bool = False
    model_name: str | None = None
    model_version: str | None = None
    r2_score: float | None = None
    target_property: str | None = None
    predicted_value: float | None = None
    lower_bound: float | None = None
    upper_bound: float | None = None
    domain_status: str = "IN_DOMAIN"
    disclaimer: str = "Predictions generated by a statistical/machine-learning model. Physical laboratory validation is required."


class OptimizationReportSectionSchema(BaseModel):
    available: bool = False
    objective_name: str | None = None
    direction: str = "MAXIMIZE"
    top_candidates: list[dict[str, Any]] = Field(default_factory=list)
    disclaimer: str = "Optimization candidates represent promising conditions under current evidence. Laboratory validation required."


class ValidationReportSectionSchema(BaseModel):
    available: bool = False
    predicted_value: float | None = None
    actual_value: float | None = None
    absolute_error: float | None = None
    relative_error_pct: float | None = None
    interval_coverage: bool = True
    model_health_status: str = "STABLE"


class ExperimentReportData(BaseModel):
    report_id: str = Field(default_factory=lambda: f"REP-{uuid.uuid4().hex[:8].upper()}")
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    software_version: str = "1.0.0-research"

    # Project metadata
    project_code: str
    project_name: str
    material: str
    biomass: str | None = None
    extract: str
    solvent: str
    synthesis_method: str
    config_version: str = "v1.0"

    # Experiment metadata
    experiment_id: str
    experiment_code: str
    title: str
    researcher: str
    status: str
    objective: str | None = None
    experiment_date: str | None = None
    created_at: datetime

    # Synthesis Parameters
    synthesis_parameters: list[dict[str, Any]] = Field(default_factory=list)

    # Samples
    samples: list[dict[str, Any]] = Field(default_factory=list)

    # Characterization & Analysis Sections
    characterization_summary: list[dict[str, Any]] = Field(default_factory=list)
    xrd: XRDReportSectionSchema = Field(default_factory=XRDReportSectionSchema)
    uvvis: UVVisReportSectionSchema = Field(default_factory=UVVisReportSectionSchema)
    electrical: ElectricalReportSectionSchema = Field(default_factory=ElectricalReportSectionSchema)
    statistics: StatisticalReportSectionSchema = Field(default_factory=StatisticalReportSectionSchema)
    ml_prediction: MLPredictionReportSectionSchema = Field(default_factory=MLPredictionReportSectionSchema)
    optimization: OptimizationReportSectionSchema = Field(default_factory=OptimizationReportSectionSchema)
    validation: ValidationReportSectionSchema = Field(default_factory=ValidationReportSectionSchema)

    # Scientific Provenance
    provenance_items: list[ProvenanceItemSchema] = Field(default_factory=list)
